# Generated by Django 2.1.7 on 2019-04-15 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mton', '0003_auto_20190411_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
    ]
